services:
  - type: web
    name: aisa-admin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_admin.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: aisa-db
          property: connectionString